import { create } from "zustand";

export const useBookingStore = create((set) => ({
  bookings: [
    {
      reservationId: 1,
      customerName: "Juan Dela Cruz",
      carModel: "Nissan",
      bookingDate: "2025-06-06",
      purpose: "Vacation",
      startDate: "2025-07-06",
      endDate: "2025-07-07",
      paymentStatus: "Paid",
      bookingStatus: "Confirmed",
    },
    {
      reservationId: 2,
      customerName: "Jason Barotu",
      carModel: "Toyota",
      bookingDate: "2025-07-06",
      purpose: "Vacation",
      startDate: "2025-08-06",
      endDate: "2025-08-07",
      paymentStatus: "Unpaid",
      bookingStatus: "Pending",
    },
    {
      reservationId: 3,
      customerName: "Karen Bot",
      carModel: "Honda",
      bookingDate: "2025-07-06",
      purpose: "Field Trip",
      startDate: "2025-08-06",
      endDate: "2025-08-07",
      paymentStatus: "Unpaid",
      bookingStatus: "Pending",
    },
    {
      reservationId: 4,
      customerName: "Harold Go",
      carModel: "Hyundai",
      bookingDate: "2025-07-06",
      purpose: "Vacation",
      startDate: "2025-08-06",
      endDate: "2025-08-07",
      paymentStatus: "Paid",
      bookingStatus: "Confirmed",
    },
    {
      reservationId: 5,
      customerName: "Harold Go",
      carModel: "Hyundai",
      bookingDate: "2025-07-10",
      purpose: "Business Trip",
      startDate: "2025-08-15",
      endDate: "2025-08-18",
      paymentStatus: "Paid",
      bookingStatus: "Confirmed",
    },
  ],
  setBookings: (rows) => set({ bookings: rows }),
}));
