import { create } from "zustand";

export const useCarStore = create((set) => ({
  cars: [
    {
      carId: 1,
      model: "Terra",
      make: "Nissan",
      type: "SUV",
      year: "2020",
      mileage: "17000",
      seats: "7",
      rentPrice: "3000",
      licensePlate: "NJS-1234",
      status: "Available",
    },
    {
      carId: 2,
      model: "Mirage",
      make: "Mitsubishi",
      type: "Sedan",
      year: "2023",
      mileage: "26990",
      seats: "5",
      rentPrice: "1800",
      licensePlate: "MBS-1234",
      status: "Maintenance",
    },
    {
      carId: 3,
      model: "Navarra",
      make: "Nissan",
      type: "Pickup",
      year: "2017",
      mileage: "18000",
      seats: "5",
      rentPrice: "2800",
      licensePlate: "GOY-1234",
      status: "Available",
    },
    {
      carId: 4,
      model: "Rio",
      make: "Kia",
      type: "Sedan",
      year: "2014",
      mileage: "20000",
      seats: "5",
      rentPrice: "1500",
      licensePlate: "NGX-1234",
      status: "Available",
    },
    {
      carId: 5,
      model: "Avanza",
      make: "Toyota",
      type: "SUV",
      year: "2023",
      mileage: "25000",
      seats: "7",
      rentPrice: "2800",
      licensePlate: "LAB-1234",
      status: "Available",
    },
  ],
  setCars: (rows) => set({ cars: rows }),
}));
