import { create } from 'zustand';

export const useScheduleStore = create((set) => ({
  reservations: [
    {
      reservationId: 1,
      customerName: 'Juan Dela Cruz',
      startDate: '2025-07-06',
      pickupTime: '08:00',
      pickupLocation: 'Plaza',
      endDate: '2025-07-07',
      dropOffTime: '17:00',
      dropOffLocation: 'Ayala',
      selfDrive: 'Yes',
      status: 'Confirmed',
    },
    {
      reservationId: 2,
      customerName: 'Elijah Go',
      startDate: '2025-07-10',
      pickupTime: '07:30',
      pickupLocation: 'IT Park',
      endDate: '2025-07-13',
      dropOffTime: '17:00',
      dropOffLocation: 'IT Park',
      selfDrive: 'No',
      status: 'Ongoing',
    },
    {
      reservationId: 3,
      customerName: 'Juan Dela Cruz',
      startDate: '2025-07-02',
      pickupTime: '08:00',
      pickupLocation: 'SM Cebu',
      endDate: '2025-07-03',
      dropOffTime: '17:00',
      dropOffLocation: 'SM Cebu',
      selfDrive: 'Yes',
      status: 'Done',
    },
    {
      reservationId: 4,
      customerName: 'Elijah Go',
      startDate: '2025-08-10',
      pickupTime: '08:00',
      pickupLocation: 'Tisa Labangon',
      endDate: '2025-08-13',
      dropOffTime: '17:00',
      dropOffLocation: 'Ayala',
      selfDrive: 'Yes',
      status: 'Confirmed',
    },
    {
      reservationId: 5,
      customerName: 'Juan Dela Cruz',
      startDate: '2025-08-15',
      pickupTime: '08:00',
      pickupLocation: 'Plaza',
      endDate: '2025-08-16',
      dropOffTime: '17:00',
      dropOffLocation: 'Plaza',
      selfDrive: 'No',
      status: 'Confirmed',
    },
    {
      reservationId: 6,
      customerName: 'Elijah Go',
      startDate: '2025-09-10',
      pickupTime: '08:00',
      pickupLocation: 'SM Seaside',
      endDate: '2025-010-13',
      dropOffTime: '17:00',
      dropOffLocation: 'Ayala',
      selfDrive: 'Yes',
      status: 'Confirmed',
    },
    {
      reservationId: 7,
      customerName: 'John Goy',
      startDate: '2025-09-10',
      pickupTime: '08:00',
      pickupLocation: 'Colonnade',
      endDate: '2025-010-13',
      dropOffTime: '17:00',
      dropOffLocation: 'E-mall',
      selfDrive: 'Yes',
      status: 'Confirmed',
    },
    {
      reservationId: 8,
      customerName: 'Fein Geer',
      startDate: '2025-010-10',
      pickupTime: '08:00',
      pickupLocation: 'SM Seaside',
      endDate: '2025-010-13',
      dropOffTime: '17:00',
      dropOffLocation: 'SM Seaside',
      selfDrive: 'No',
      status: 'Confirmed',
    },
    {
      reservationId: 9,
      customerName: 'Fein Geer',
      startDate: '2025-010-15',
      pickupTime: '08:00',
      pickupLocation: 'Lahug',
      endDate: '2025-010-18',
      dropOffTime: '17:00',
      dropOffLocation: 'Banilad',
      selfDrive: 'No',
      status: 'Confirmed',
    },
    {
      reservationId: 10,
      customerName: 'Fein Geer',
      startDate: '2025-010-21',
      pickupTime: '08:00',
      pickupLocation: 'Banilad',
      endDate: '2025-010-23',
      dropOffTime: '17:00',
      dropOffLocation: 'Talamban',
      selfDrive: 'No',
      status: 'Confirmed',
    },
  ],
  setReservations: (rows) => set({ reservations: rows }),
  updateReservationStatus: (reservationId, newStatus) =>
    set((state) => ({
      reservations: state.reservations.map((reservation) =>
        reservation.reservationId === reservationId
          ? { ...reservation, status: newStatus }
          : reservation
      ),
    })),
}));
